app = "kompli-bot"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080       # если твой код слушает HTTP
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
