app = "testbot"   # замени на имя приложения на Fly

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python bot.py"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256MB"
