# fly.toml app configuration file generated for ANY telegram bot
# Имя приложения Fly подставляется автоматически при деплое

app = "PLACEHOLDER_APP_NAME"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python bot.py"

[[vm]]
  size = "shared-cpu-1x"
  memory = "256MB"
