# ===== fly.toml =====
app = "kompli-bot"            # <--- ПОМЕНИ на своё имя приложения на Fly
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[processes]
  app = "python main.py"

# Если ты вдруг добавишь healthcheck — можно добавить блок [checks], но для воркера это не обязательно.
