app = "testbot"   # поменяй на уникальное имя
primary_region = "sin"      # Токио — ближе всего к KR; можно "hkg" или "sin"

kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "Dockerfile"

[env]
  PYTHONUNBUFFERED = "1"

[processes]
  app = "python main.py"

# Автоперезапуск, если процесс упал
[checks]
  [checks.alive]
    type = "process"
    interval = "15s"
    timeout = "5s"
    grace_period = "10s"
